import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import localFont from "next/font/local";

const barlow = localFont({
  src: [
    {
      path: "../fonts/barlow/Barlow-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/barlow/Barlow-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/barlow/Barlow-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-barlow",
});


export const metadata: Metadata = {
  title: "WhiteLabel Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={barlow.variable}>
      <body
        className={`font-barlow antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
